services:
  web:
    build: .
    container_name: noszona-web
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: noszona-node-red
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    environment:
      - TZ=Atlantic/Cape_Verde
      - NODE_RED_CREDENTIAL_SECRET=troca_esta_chave_por_uma_senha_forte
    restart: unless-stopped

volumes:
  node_red_data: